import React from 'react'
import Head from "next/head";
import MainBanner from '../components/sub-page/MainBanner'
import { useLandingPage } from '@/app/hooks/useLandingPage';
import { Categories, Footer, Header } from '../components/landing-page';
import HelpSection from '../components/sub-page/HelpSection';
import BetainosBanner from '../components/sub-page/BetainosBanner';
import Testimonials from '../components/sub-page/Testimonials';
import { DevelopmentServices } from '../components/sub-page/DevelopmentServices';
import { ServicesBox } from '../components/sub-page/ServicesBox';


const Index = () => {
    const { data, isLoading } = useLandingPage();
    const pageData = data && data[0];
    
  return (
    <>
    <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
        />
      </Head>
        <Header pageData={pageData} />
        <MainBanner/>
        <DevelopmentServices/>
        <ServicesBox/>
        <BetainosBanner/>
        <Categories />
        <HelpSection />
        <Testimonials />
        <Footer pageData={pageData} />
    </>
  )
}

export default Index