import { useLandingPage } from "@/app/hooks/useLandingPage";
import Head from "next/head";
import { Categories, Footer, Header } from '../components/landing-page';
import { AdvertisementBox, Banner, ProfessionalBox } from '../components/sub-page';

const Index = () => {
  const { data } = useLandingPage();
  const pageData = data && data[0];
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
        />
      </Head>
      <Header pageData={pageData} />
      <Banner />
      <AdvertisementBox />
      <ProfessionalBox />
      <Categories />
      <Footer pageData={pageData} />
    </>
  );
};

export default Index;
