import React from "react";
import Head from "next/head";
import { Header } from '../components/landing-page/Header';
import { EmployeeForm } from '../components/sub-page/EmployeeForm';
import { BlogCard } from '../components/sub-page/BlogCard';
import { AdvertisementBox2 } from '../components/sub-page/AdvertisementBox2';
import { Footer } from "../components/landing-page/Footer";

const Index = () => {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
        />
      </Head>
      <Header />
      <EmployeeForm />
      <BlogCard />
      <AdvertisementBox2  />
      <BlogCard />
      <Footer />
    </>
  );
};

export default Index;
