import React from 'react';
import Head from "next/head";
import { Categories, Footer, Header } from '../components/landing-page';
import { useLandingPage } from '@/app/hooks/useLandingPage';
import { MainContactBox } from '../components/sub-page/MainContactBox';

const Index = () => {
  const { data, isLoading } = useLandingPage();  // Moved inside the function
  const pageData = data && data[0];

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
        />
      </Head>
      <Header pageData={pageData} />
      <MainContactBox/>
      <Footer pageData={pageData} />
    </>
  );
};

export default Index;
