import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";
import { Header } from "./components/landing-page/Header";
import { AdvertiseBanner } from "./components/landing-page/AdvertiseBanner";
import { AdditionBox } from "./components/landing-page/AdditionBox";
import { Categories } from "./components/landing-page/Categories";
import { Footer } from "./components/landing-page/Footer";
import { Contact } from "./components/landing-page/Contact";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" />
      </Head>
      <Header/>
      <AdvertiseBanner/>
      <Contact/>
      <AdditionBox/>
      <Categories/>
      <Footer/>
    </>
  );
}
