import Head from "next/head";
import { useEffect } from "react";
import { Directory, Header, Footer, AdvertiseBanner, Categories, HeroSection } from "./components/landing-page";
import { useLandingPage } from "@/app/hooks/useLandingPage";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export default function Home() {
  useEffect(() => {
    import('bootstrap/dist/js/bootstrap.bundle.min.js');
  }, []);
  const { data, isLoading } = useLandingPage();
  const pageData = data && data[0];
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

      </Head>
      {
        isLoading ? <>
          <div className="loader-mask" >
    <div className="loader">
        <div></div>
        <div></div>
    </div>
</div>
        </> : <>

          <Header pageData={pageData} />
          {
            pageData?.Advertisement && <AdvertiseBanner pageData={pageData} />
          }

          <HeroSection pageData={pageData} />
          <Directory pageData={pageData} />
          <Categories pageData={pageData} />
          <Footer pageData={pageData} />
        </>
      }

    </>
  );
}
